from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def create_pdf(report_text):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.HexColor("#0F4C81")

    heading = styles["Heading2"]
    heading.textColor = colors.HexColor("#0F4C81")

    normal = styles["BodyText"]

    story = []

    # ---------------------------------
    # Title
    # ---------------------------------

    story.append(
        Paragraph(
            "AI Career Advisor",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Career Analysis Report",
            heading
        )
    )

    story.append(
        Spacer(1, 0.5 * cm)
    )

    # ---------------------------------
    # Parse report
    # ---------------------------------

    lines = [
        line.strip()
        for line in report_text.split("\n")
        if line.strip()
    ]

    values = {}

    for i in range(len(lines) - 1):

        values[lines[i]] = lines[i + 1]

    # ---------------------------------
    # Summary Table
    # ---------------------------------

    table_data = [

        ["Field", "Value"],

        [
            "Predicted Category",
            values.get("Predicted Category:", "-")
        ],

        [
            "Prediction Confidence",
            values.get("Prediction Confidence:", "-")
        ],

        [
            "Resume Strength",
            values.get("Resume Strength:", "-")
        ],

        [
            "Resume Quality",
            values.get("Resume Quality:", "-")
        ],

        [
            "Job Description Match",
            values.get(
                "Job Description Match:",
                "N/A"
            )
        ],

    ]

    table = Table(
        table_data,
        colWidths=[7 * cm, 8 * cm]
    )

    table.setStyle(
        TableStyle(

            [

                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#0F4C81"),
                ),

                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),

                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.whitesmoke,
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, 0),
                    10,
                ),

            ]

        )
    )

    story.append(table)

    story.append(
        Spacer(1, 0.6 * cm)
    )

    # ---------------------------------
    # Full Report
    # ---------------------------------

    story.append(
        Paragraph(
            "Detailed Analysis",
            heading
        )
    )

    story.append(
        Spacer(1, 0.3 * cm)
    )

    for line in lines:

        story.append(
            Paragraph(
                line,
                normal
            )
        )

    story.append(
        Spacer(1, 0.8 * cm)
    )

    # ---------------------------------
    # Footer
    # ---------------------------------

    footer = Paragraph(

        "<font color='gray'>"
        "Generated by AI Career Advisor<br/>"
        "SRH University of Applied Sciences<br/>"
        "Sara Hodzic & Mithat Misirlic • 2026"
        "</font>",

        styles["Italic"]

    )

    story.append(footer)

    doc.build(story)

    buffer.seek(0)

    return buffer