def generate_report(
    predicted_category,
    confidence,
    best_match,
    strength_score,
    resume_level,
    job_match_score=None
):
    """
    Generate a text career report.
    """

    report = f"""
===============================
      AI CAREER ADVISOR
===============================

RESUME ANALYSIS

Predicted Category:
{predicted_category}

Prediction Confidence:
{confidence:.2f}%

Resume Strength:
{strength_score}/100

Resume Quality:
{resume_level}

"""

    if job_match_score is not None:

        report += f"""
Job Description Match:
{job_match_score:.2f}%
"""

    report += f"""

-------------------------------

BEST JOB RECOMMENDATION

Job Title:
{best_match['title']}

Match Score:
{best_match['score']:.2f}%

Recommendation Level:
{best_match['recommendation_level']}

-------------------------------

MATCHING SKILLS

"""

    if best_match["matching_skills"]:

        for skill in best_match["matching_skills"]:

            report += f"- {skill}\n"

    else:

        report += "No matching skills found.\n"

    report += "\n"

    report += "MISSING SKILLS\n\n"

    if best_match["missing_skills"]:

        for skill in best_match["missing_skills"][:10]:

            report += f"- {skill}\n"

    else:

        report += "No missing skills.\n"

    report += """

===============================
Generated by AI Career Advisor
===============================
"""

    return report